[mongo]
Addresses= ["127.0.0.1:27017"]
DbName = "test_mongo"
User= ""
Password= ""
Login = true

[mysql]
user = "root"
password = "123456"
host = "127.0.0.1:3306"
database = "test_mysql"
charset =  "utf8mb4"

[redis]
Addresses = ["127.0.0.1:6379"]
Password = ""
MaxIdle = 30
MaxActive = 30
IdleTimeout = 200
Cluster = 0
DBNumber = 0

